### PR TITLE
added hover to features card!

### PR DESCRIPTION
**Pull request by Shekhar-Raj**
I first added the images as using the assets folder as the image url was not working. Then applied the hover feature to the feature cards along with the box shadow.

Before:
image

After:

image

### CODE REVIEW

**Comment by Shekhar-Raj** [comment]
> @Shekhar-Raj you branch is having conflicts fork the project again and make changes . always fork the website again before making changes



> @Shekhar-Raj you branch is having conflicts fork the project again and make changes . always fork the website again before making changes

Sorry , it's my first time! So i need to fork again and then save changes in my branch and then give a pull request ? Correct ?

**Comment by Shekhar-Raj** [comment]
> @Shekhar-Raj np yes just remember that before making changes fork the website so you dont have any conflict, after your branch is merged delete it and fork again

do i need to delete my old fork?

**Comment by Shekhar-Raj** [comment]
Can u Please check it is showing --> This branch is not behind the upstream GarimaSingh0109/Resum-Resume:main   on my fork repository

**Comment by GarimaSingh0109** [comment]
Ig this happened because you made changes in main branch dont do that rather create a new branch and do changes in that branch

**Comment by Shekhar-Raj** [comment]
Thank You! for your support!

**Pull request merged**
