### PR TITLE
Update signup.html

### PR DESCRIPTION
**Pull request by Lekkhasri**
The password criteria has been updated and the signupForm holder has been added

### CODE REVIEW

**Review by GarimaSingh0109 — APPROVED** [review]

**Comment by GarimaSingh0109** [comment]
@Lekkhasri  always add ss of ur work it will be helpful for you

**Comment by Lekkhasri** [comment]
@GarimaSingh0109 Thank you mam I will add in further projects

**Comment by Lekkhasri** [comment]
@GarimaSingh0109 There is no label assigned can you assign it

**Comment by Lekkhasri** [comment]
@GarimaSingh0109 mam you merged the file but not added the labels yet please add it mam 
#101 this was the issue i rectified it

**Pull request merged**
