### PR TITLE
ADDED FAQs PAGE TO THE PROJECT #200

### PR DESCRIPTION
**Pull request by sahhoArjun097**
ADDED FAQs PAGE TO THE PROJECT

issue number :  #200

This pull request introduces key updates and improvements to the project, aimed at enhancing functionality, performance, and user experience. Below is a summary of the changes and the rationale for their implementation.

Added a fully responsive and functional FAQ section to address common user queries, improving accessibility and support for users on the platform.
Included expand/collapse functionality to improve navigation, allowing users to find relevant information quickly and easily.

## Types of Changes

_Please check the boxes that apply:_

- [y ] Bugfix (non-breaking change that resolves an issue)
- [y ] New feature (non-breaking change that introduces new functionality)
- [ ] Breaking change (modification that may cause existing functionality to not work as expected)
- [ ] Documentation update (changes to documentation content)
- [ ] Other (please specify):

## Checklist

_Please ensure the following criteria are met:_

- [y ] My code adheres to the project's style guidelines
- [y ] I have conducted a self-review of my code
- [y ] I have commented my code, especially in complex areas
- [ y] I have updated the documentation to reflect my changes
- [ y] My changes do not introduce new warnings
- [ y] My changes maintain the current system's functionality and pass all existing test cases
- [y ] I have added tests to verify the effectiveness of my fix or feature
- [y ] All new and existing unit tests pass locally with my changes

https://github.com/user-attachments/assets/43cdcfa5-65c8-470f-8ce1-dbb4e644fcc2

## Additional Information

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and lvl.

### CODE REVIEW

**Review by GarimaSingh0109 — CHANGES_REQUESTED** [review]
Hey @sahhoArjun097  can you change the color to the color pallet in the 
https://coolors.co/palette/231942-5e548e-9f86c0-be95c4-e0b1cb
#231942, #5E548E, #9F86C0, #BE95C4, #E0B1CB

**Comment by sahhoArjun097** [comment]
please review the change

**Comment by sahhoArjun097** [comment]
image

**Review by GarimaSingh0109 — APPROVED** [review]

**Comment by sahhoArjun097** [comment]
ma'am please give me lvl 2 for this i created a while FAQs section with proper functionality

**Pull request merged**
