### PR TITLE
Implemented Dynamic Dark/Light Mode Toggle with Local Storage Support

### PR DESCRIPTION
**Pull request by meghanakn473**
I’ve added a dynamic dark/light mode toggle to the site, allowing users to easily switch between the two themes. The best part is that the site remembers the user’s preference using localStorage, so they won’t have to keep switching every time they visit. By default, the site starts in light mode, but if someone prefers dark mode, that choice will be saved for future visits. I’ve tested it across different devices and pages to make sure it looks good and works smoothly. This should make the site more user-friendly and customizable!
Light mode
Screenshot (135)
Dark mode
Screenshot (136)

### CODE REVIEW

**Comment by GarimaSingh0109** [comment]
Do mention the issue you are refering to

**Comment by meghanakn473** [comment]
> Do mention the issue you are refering to

the issue is abt able to enable dark mode for the website

**Review by meghanakn473 — COMMENTED** [review]
i have reviewed and changed the conflicts, can you please recheck

**Comment by GarimaSingh0109** [comment]
@meghanakn473 i m asking you to mention the issue no which you have created the pr for

**Comment by GarimaSingh0109** [comment]
@meghanakn473  your files still have conflict do one thing fork the project again and make changes in that

**Pull request closed without merging**
