### PR TITLE
Navbar Responsiveness

### PR DESCRIPTION
**Pull request by itsbhh**
1. Responsive About Section: Made the About section fully responsive, ensuring that it adjusts seamlessly across different screen sizes, providing an optimal viewing experience.

2. Sticky Navbar Error Resolution: Addressed an issue where the sticky navbar obscured the content below. A margin has been added to the main content area, ensuring that all content is clearly visible and accessible, regardless of screen size.

3. Sidebar Implementation: Integrated a responsive sidebar that appears for screen widths less than 760px, providing easy navigation across the site. The sidebar is designed to be consistent across all pages, including the About and Index pages, enhancing user experience.

4. Navbar Responsiveness: The navigation bar on the Resume Builder page has been made responsive, ensuring that links are easily accessible on smaller screens.

5. Additional Adjustments : Implemented further adjustments to the layout and design to ensure a cohesive and user-friendly interface, including styling changes to enhance aesthetics.

These updates aim to improve the overall functionality and accessibility of the application, making it easier for users to navigate and interact with the content.

**_### Please label this under GSSOC'24 extd and Hacktoberfest-accepted and pls add the label of the level I did contribute._**

image
image
image
image
image

### CODE REVIEW

**Comment by Vaibhav22p-qw** [comment]
@GarimaSingh0109 , please review

**Comment by itsbhh** [comment]
> Stick to the color pallet

HEY I HAVE CHANGED THE COLOURS ACCORDING TO YOUR GIVEN PALLETE.
#9F86C0 (Light Purple):

Background of the sidebar: This soft purple serves as the main background color of the sidebar when the screen width is less than 768px.
#231942 (Dark Purple):

Link text color: The links inside the sidebar use this dark purple color, creating a nice contrast against the light purple background.
#BE95C4 (Muted Pink):

Link hover background color: When a user hovers over a link in the sidebar, the background changes to a subtle muted pink, adding a smooth visual transition.
#E0B1CB (Soft Pink):

Icon color: The icons within the sidebar use this soft pink color, which stands out while still being cohesive with the overall color palette.
Close button hover color: When the user hovers over the close button, it changes to this soft pink.


image
**I HAVE EVEN MENTIONED ABOVE WHICH COLOUR FROM THE GIVEN PALLETE IS USED FOR WHICH TASK
### Please label this under GSSOC'24 extd and Hacktoberfest-accepted and pls add the label of the level I did contribute.**

**Review by GarimaSingh0109 — APPROVED** [review]

**Comment by GarimaSingh0109** [comment]
@itsbhh i have approved your pr but it has lots of conflicts and i cant resolve all of them i have resolved 2 files do the rest and pin me again so that pr can be merged

**Comment by itsbhh** [comment]
> @itsbhh i have approved your pr but it has lots of conflicts and i cant resolve all of them i have resolved 2 files do the rest and pin me again so that pr can be merged

HEY I RESOLVED THE CONFLICTS.

**Pull request merged**
