### PR TITLE
Improving Header Aesthetics

### PR DESCRIPTION
**Pull request by YOGINIMAHIMA1**
Remove the dot in the header section, as it affects the overall appearance. I made changes to the header by removing the . within the <span> tag to enhance the page's visual appeal.

### CODE REVIEW

**Comment by YOGINIMAHIMA1** [comment]
Modiefied header section

**Comment by GarimaSingh0109** [comment]
@YOGINIMAHIMA1 add ss of ur work it will be helpful for you

**Review by GarimaSingh0109 — APPROVED** [review]

**Comment by YOGINIMAHIMA1** [comment]
image

Removed that . and <span> tag from header section.

**Comment by YOGINIMAHIMA1** [comment]
image
Removed dot @GarimaSingh0109 .

**Comment by RadhikaMalpani1702** [comment]
Hi @YOGINIMAHIMA1, 

I'm the Program Manager for GSSoC Extended, I have reviewed your PR and noticed that it contains only a single line of change. Unfortunately, this does not qualify for a Level 1 label (10 points). Kindly avoid requesting level labels for such minor PRs. Additionally, please ensure that you first create and get an issue assigned before submitting a PR.

**Comment by YOGINIMAHIMA1** [comment]
@RadhikaMalpani1702 i have already created issue for this and second thing my few pr already get llabel but they points are not increased yet

**Pull request merged**
