### PR TITLE
[FIX] Landing Page Error Fixed

### LINKED ISSUE #140: [BUG] Landing page ERROR
## ERROR in landing page
- Source code is Showing

## Screenshot
image

### PR DESCRIPTION
**Pull request by 4F24L**
## Fixed error on landing page
- Fixes #140 

## Before :
image

## After ✅ : 
image

### CODE REVIEW

**Comment by 4F24L** [comment]
@GarimaSingh0109 Can you review this code ??

**Review by akash70629 — COMMENTED** [review]
These lines are comments only, so how can anyone view them without uncommenting? Additionally, I couldn't replicate the issue you mentioned on the live website. Could you provide more context or clarify the problem? @4F24L

**Comment by 4F24L** [comment]
This issue was there, now even I can't see it !!1

**Comment by akash70629** [comment]
> This issue was there, now even I can't see it !!

@4F24L Are you certain you saw them on the live website, or was it on localhost? If it was localhost, perhaps they were somehow uncommented. If you saw them on the live website, it could be a glitch or another issue.😂

**Comment by 4F24L** [comment]
> > This issue was there, now even I can't see it !!
> 
> @4F24L Are you certain you saw them on the live website, or was it on localhost? If it was localhost, perhaps they were somehow uncommented. If you saw them on the live website, it could be a glitch or another issue.😂

On live site

**Review by GarimaSingh0109 — APPROVED** [review]

**Comment by akash70629** [comment]
@4F24L congratulations bro !!! Finally it's merged 😂

**Pull request merged**
