### PR TITLE
Change colour , font -size in the project

### PR DESCRIPTION
**Pull request by Dipanita45**
#254 

### Summary
Change in the background colour , add effect in the project.

### Details
Change the text size, text colour, background colour of the icon , navbar, footer to increase readability and wherever  required

## Css changes 

_Please check the boxes that apply:_

- [ yes] Bugfix (non-breaking change that resolves an issue)
- [no ] New feature (non-breaking change that introduces new functionality)
- [ no] Breaking change (modification that may cause existing functionality to not work as expected)
- [no ] Documentation update (changes to documentation content)
- [ yes] Other (please specify):
- increases readability

## Checklist
I am gossoc-2024 extd

### CODE REVIEW

**Comment by GarimaSingh0109** [comment]
@Dipanita45  #269

**Comment by Dipanita45** [comment]
I have to do #269

**Comment by Dipanita45** [comment]
Please review my pull request and label

**Comment by Dipanita45** [comment]
#312 
 please review my pull request @GarimaSingh0109

**Comment by GarimaSingh0109** [comment]
@Dipanita45 this is not the right repo

**Pull request closed without merging**
