### PR TITLE
Enhanced Resum Resume Project: Streamlined Design and Functionality

### PR DESCRIPTION
**Pull request by Sneha22072005**
We revamped the Resum Resume web application by improving multiple sections, including home, about me, resume builder, login, and signup pages. The design now boasts a modern minimalist color scheme with a deep teal, soft gold, and dark slate palette, creating a professional and cohesive user experience. Key improvements include a consistent layout across all pages, a visually appealing form design for the login and signup sections, and responsive footer elements. The project also features interactive hover effects, centered logos, and smooth transitions to enhance usability while maintaining a clean, elegant appearance.

issue #92 

Pls review @GarimaSingh0109 @Vaibhav22p-qw

### CODE REVIEW

**Comment by GarimaSingh0109** [comment]
Add screenshot of your work

**Comment by Sneha22072005** [comment]
image
image
image
image
image
image
image
image
I haven't worked much on the fonts in the footer as I was hoping for a feedback first. Though additionally I have added the functionality of going to the home page by clicking the logo on both signup and login pages. The theme is modern minimalist to give the website a more professional view

**Comment by GarimaSingh0109** [comment]
@Sneha22072005 good job 👏  you can create a new issue for footer as well as I would like you to remove those linked in icons from about page

**Comment by Sneha22072005** [comment]
of course but can u pls point it out where in the footer of about me? I dont really see any links there..

**Comment by Hemraj-7** [comment]
Hi I'm Hem Raj. I want to enhance footer because it is don't showing properly

Screenshot 2024-10-07 163335

**Pull request merged**
