### PR TITLE
This PR is related to Issue #489. privacypolicy.html has been added

### PR DESCRIPTION
**Pull request by Priyank00007**
# Pull Request for Resum-Resume 💡

## Issue Title : Privacy Policy Page Missing
 Name: Priyank Jain
GItHub Id: Priyank00007
Email Id: priyankjain795@gmail.com

Closes: #489

I have created a privacy policy page with same UI of the about page of Resum Resume.

## Type of change ☑️

What sort of change have you made:

- [x] New feature: Privacy Policy page is being displayed on the website.

image

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
-  [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by GarimaSingh0109** [comment]
@Priyank00007 you have created a button for this page in navbar??

**Review by GarimaSingh0109 — APPROVED** [review]

**Comment by Priyank00007** [comment]
> @Priyank00007 you have created a button for this page in navbar?? if not do create a button for the same

I have created the button for this on navbar of privacy policy page but not on all pages so should i create the button for all pages?

**Comment by Priyank00007** [comment]
> @Priyank00007 you have created a button for this page in navbar?? if not do create a button for the same

I have created the button for all navbar in all pages
image
image

**Comment by Priyank00007** [comment]
@GarimaSingh0109 is this issue completed?

**Comment by Priyank00007** [comment]
@GarimaSingh0109 mam can u close this issue please

**Comment by Priyank00007** [comment]
@GarimaSingh0109 mam can u merge it with main

**Comment by Priyank00007** [comment]
@GarimaSingh0109  I have removed the conflicts present

**Comment by Priyank00007** [comment]
@GarimaSingh0109  can u close this issue please

**Comment by Priyank00007** [comment]
@GarimaSingh0109 mam either close this PR or tell me if there are any corrections left coz until u close this PR, I wont get any points for it so kindly close this PR soon

**Pull request merged**
