### PR TITLE
added gsap and navbar design

### LINKED ISSUE #162: animations in a home page
Objective: I propose enhancing the homepage with text animations using GSAP (GreenSock Animation Platform) to improve user engagement and make the interface more dynamic.

Details:

Animate heading and subheading text on page load.
Include subtle fade-in or slide-in animations for improved visual appeal.
Ensure animations are responsive and do not affect performance on lower-end devices.
Will add comments to code to ensure clarity for future contributors.
Please assign this issue to me, as I would love to work on it. I am also a contributor in GGSOCExt 24 , hacktoberfest.

Looking forward to your feedback!

### PR DESCRIPTION
**Pull request by priyashuu**
fixes #162

### CODE REVIEW

**Comment by priyashuu** [comment]
please reviewed it na , can you please see the change , and merge it na

**Comment by priyashuu** [comment]
its been 3 days , can u please review it and merge it please

**Review by GarimaSingh0109 — APPROVED** [review]

**Comment by GarimaSingh0109** [comment]
Your pr isn't well written write in proper format

**Comment by GarimaSingh0109** [comment]
@priyashuu You can create a new issue regarding hover effect as black doesnt suit here make changes

**Comment by priyashuu** [comment]
ok mam

**Pull request merged**
